name: Log File Changes

on:
  push:
    paths:
      - 'index.html'  # 監視したい特定のファイルのパス

jobs:
  log_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep 'index.html'; then
            echo "File has changed."
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Log file changes
        if: env.changed == 'true'
        run: |
          echo "Changes in file.txt:"
          git show HEAD:index.html
